on:
  pull_request:
    branches:
      - master
      - cpu-design
      - testbench
  push:
    branches:
      - master
      - cpu-design
      - testbench

name: Continuous Integration

jobs:
  test:
    runs-on: ubuntu-latest
    container: neeld/mips
    name: Run Testbench
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Temp Files
        working-directory: ./test
        run: ./generate_all_c_files.sh
      - name: Run Testbench (Bus)
        run: ./test/test_mips_cpu_bus.sh
      - name: Run Testbench (Harvard)
        run: ./test/test_mips_cpu_harvard.sh rtl/cpu_design_harvard
  lint:
    runs-on: ubuntu-latest
    container: neeld/mips
    name: Run Verible Linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Linter (Harvard)
        working-directory: ./rtl/cpu_design_harvard
        run: verible-verilog-lint --lint_fatal=false *.v
      - name: Run Linter (Bus)
        working-directory: ./rtl/cpu_design_bus
        run: verible-verilog-lint --lint_fatal=false *.v
